version: "3"
services:
  stecker-club-monitor:
    depends_on:
      - club-monitor-db
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "club-monitor"
    hostname: club-monitor
    links:
      - club-monitor-db:mysql
    ports:
      - "8082:80"
    volumes:
      - /var/lib/steckercontent/storage/cdn/upload:/var/www/html/common/uploads/
      - /var/lib/steckercontent/storage/club-monitor/config.php:/var/www/html/common/config.php
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "PathPrefixStrip:/club-monitor"
    networks:
      - stecker
  club-monitor-db:
    image: mysql:5.7
    hostname: club-monitor-db
    volumes:
       - /var/lib/steckercontent/mysql/club-monitor:/var/lib/mysql
    restart: always
    env_file:
       - sqlpwd.env
    networks:
      - stecker



networks:
  stecker:
    external: true


  
